#!/bin/bash



if [[ "$1" = "-n[123]" ]]; then
	number_of_lines=$(echo $1 | cut -c 3-)
	start_line=$2
else
	number_of_lines=10
	start_line=$1	
fi

for i in $@
do
	cat $filename | tail -n[line to start from] | head -n[how many lines left]
done

