#!/bin/bash

if [[ "$1" == "-n"* ]]; then
	number_of_lines=$(echo $1 | cut -c 3-)
	start_line=$2
	shift
	shift
else
	number_of_lines=10
	start_line=$1
	shift	
fi

echo -e "Printing $number_of_lines lines starting from line $start_line \n"

for i in $@
do

	echo -e "Processing file $i \n"

	total_lines=$(cat $i | wc -l)

	if [ $total_lines -le $start_line ]; then
		echo -e "Not enough lines, defaulting to first line... \n"
		start_line=1
	fi

	tail_from=$(($total_lines - $start_line + 1))
	
	if [ $tail_from -le $number_of_lines ]; then
		number_of_lines=$(($tail_from-1))
	fi

	cat "$i" | tail -n$tail_from | head -n$number_of_lines
	
done

